# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c322edd81b695ba285b825aa3b5a0e1ff3de6e87f92252d27c0a220e5874b4dfd9868437c6e7330136b74d36d5939a8f37a958d90dfdb3450dcb526a6e2dfd

test:
  secret_key_base: c783c5c898c03b236919e1673f994f37242f2fde96e1e60f4f4082c019fe8f0929587f5cb7f4e1b2fefc150c2114461d74c55e51debb7e6a6b5e42c5edb6d7f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
